import numpy as np
import scipy.io.wavfile as wf
import matplotlib.pyplot as mp
sample_rate, sample_data = wf.read('original.wav')
repeat_data = np.tile(sample_data, (3, 1))
wf.write('repeated.wav', sample_rate, repeat_data)
mp.gcf().set_facecolor(np.ones(3) * 240 / 255)
mp.subplot(221)
mp.title('Original Left', fontsize=16)
mp.xlabel('Time', fontsize=12)
mp.ylabel('Sample', fontsize=12)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.plot(sample_data[:,0], c='darkorange', label='Left')
mp.legend()
mp.subplot(222)
mp.title('Original Right', fontsize=16)
mp.xlabel('Time', fontsize=12)
mp.ylabel('Sample', fontsize=12)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.plot(sample_data[:,1], c='deepskyblue', label='Right')
mp.legend()
mp.subplot(223)
mp.title('Repeated Left', fontsize=16)
mp.xlabel('Time', fontsize=12)
mp.ylabel('Sample', fontsize=12)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.plot(repeat_data[:,0], c='orangered', label='Left')
mp.legend()
mp.subplot(224)
mp.title('Repeated Right', fontsize=16)
mp.xlabel('Time', fontsize=12)
mp.ylabel('Sample', fontsize=12)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.plot(repeat_data[:,1], c='dodgerblue', label='Right')
mp.tight_layout()
mp.show()
