import numpy as np
import scipy.misc as sm
import scipy.ndimage as sn
import matplotlib.pyplot as mp
# 加载图像
image1 = sm.ascent().astype(np.float32)
# 均值滤波
image2 = sn.median_filter(image1, (42, 42))
# 旋转图像
image3 = sn.rotate(image1, angle=45)
# 浮雕图像
image4 = sn.prewitt(image1)
mp.gcf().set_facecolor(np.ones(3) * 240 / 255)
mp.subplot(221)
mp.title('Original', fontsize=16)
mp.xlabel('Width', fontsize=12)
mp.ylabel('Height', fontsize=12)
ax = mp.gca()
ax.xaxis.set_major_locator(mp.MultipleLocator(128))
ax.xaxis.set_minor_locator(mp.MultipleLocator(32))
ax.yaxis.set_major_locator(mp.MultipleLocator(128))
ax.yaxis.set_minor_locator(mp.MultipleLocator(32))
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.imshow(image1, cmap='gray')
mp.subplot(222)
mp.title('Median', fontsize=16)
mp.xlabel('Width', fontsize=12)
mp.ylabel('Height', fontsize=12)
ax = mp.gca()
ax.xaxis.set_major_locator(mp.MultipleLocator(128))
ax.xaxis.set_minor_locator(mp.MultipleLocator(32))
ax.yaxis.set_major_locator(mp.MultipleLocator(128))
ax.yaxis.set_minor_locator(mp.MultipleLocator(32))
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.imshow(image2, cmap='gray')
mp.subplot(223)
mp.title('Rotated', fontsize=16)
mp.xlabel('Width', fontsize=12)
mp.ylabel('Height', fontsize=12)
ax = mp.gca()
ax.xaxis.set_major_locator(mp.MultipleLocator(128))
ax.xaxis.set_minor_locator(mp.MultipleLocator(32))
ax.yaxis.set_major_locator(mp.MultipleLocator(128))
ax.yaxis.set_minor_locator(mp.MultipleLocator(32))
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.imshow(image3, cmap='gray')
mp.subplot(224)
mp.title('Prewitted', fontsize=16)
mp.xlabel('Width', fontsize=12)
mp.ylabel('Height', fontsize=12)
ax = mp.gca()
ax.xaxis.set_major_locator(mp.MultipleLocator(128))
ax.xaxis.set_minor_locator(mp.MultipleLocator(32))
ax.yaxis.set_major_locator(mp.MultipleLocator(128))
ax.yaxis.set_minor_locator(mp.MultipleLocator(32))
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.imshow(image4, cmap='gray')
mp.tight_layout()
mp.show()
