import numpy as np
import matplotlib.pyplot as mp
import mpl_toolkits.axes_grid1 as mg
x1 = np.linspace(-5, 5, 501)
y1 = np.sinc(x1)
x2 = np.outer(x1, x1)
y2 = np.sinc(x2)
mp.gcf().set_facecolor(np.ones(3) * 240 / 255)
mp.subplot(121)
mp.title('Sinc-1D Function', fontsize=20)
mp.xlabel('x', fontsize=14)
mp.ylabel('y', fontsize=14)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
mp.plot(x1, y1, c='dodgerblue', label='Sinc')
mp.subplot(122)
mp.title('Sinc-2D Function', fontsize=20)
mp.xlabel('x', fontsize=14)
mp.ylabel('y', fontsize=14)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
im = mp.imshow(y2, extent=(-5, 5, -5, 5), cmap='jet')
dv = mg.make_axes_locatable(mp.gca())
ca = dv.append_axes('right', '6%', pad='5%')
cb = mp.colorbar(im, cax=ca)
cb.set_label('sinc-2D', fontsize=14)
mp.legend()
mp.show()
