import numpy as np
import matplotlib.pyplot as mp
u = np.linspace(-2.5, 2.5, 501)
x, y = np.meshgrid(u, u)
z = np.sinc(x * y)
mp.gcf().set_facecolor(np.ones(3) * 240 / 255)
mp.subplot(121)
mp.title('Ordinary Contour', fontsize=16)
mp.xlabel('x', fontsize=12)
mp.ylabel('y', fontsize=12)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
cntr = mp.contour(x, y, z, 5, cmap='jet')
mp.clabel(cntr, inline_spacing=1, fmt='%.2f', fontsize=8,
	cmap='jet')
mp.colorbar(cntr).set_label('sinc-2D', fontsize=12)
mp.subplot(122)
mp.title('Filled Contour', fontsize=16)
mp.xlabel('x', fontsize=12)
mp.ylabel('y', fontsize=12)
mp.tick_params(labelsize=10)
mp.grid(linestyle=':')
cntrf = mp.contourf(x, y, z, 20, cmap='jet')
mp.colorbar(cntrf).set_label('sinc-2D', fontsize=12)
mp.tight_layout()
mp.show()
